config/routes.rb
PlV1::Application.routes.draw do

  root :to =>'users#new'

  resources :promotions

  resources :users

end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  attr_accessible :content, :download_link, :download_name, :email, :map_link, :password, :phone, :photo1, :photo2, :photo3, :photo4, :subtitle, :title, :user_id, :video_embed
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :firstname, :lastname
  has_many :promotions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  # GET /promotions
  # GET /promotions.json
  def index
    @promotions = Promotion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @promotions }
    end
  end

  # GET /promotions/1
  # GET /promotions/1.json
  def show
    @promotion = Promotion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @promotion }
    end
  end

  # GET /promotions/new
  # GET /promotions/new.json
  def new
    @promotion = Promotion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @promotion }
    end
  end

  # GET /promotions/1/edit
  def edit
    @promotion = Promotion.find(params[:id])
  end

  # POST /promotions
  # POST /promotions.json
  def create
    @promotion = Promotion.new(params[:promotion])

    respond_to do |format|
      if @promotion.save
        format.html { redirect_to @promotion, notice: 'Promotion was successfully created.' }
        format.json { render json: @promotion, status: :created, location: @promotion }
      else
        format.html { render action: "new" }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /promotions/1
  # PUT /promotions/1.json
  def update
    @promotion = Promotion.find(params[:id])

    respond_to do |format|
      if @promotion.update_attributes(params[:promotion])
        format.html { redirect_to @promotion, notice: 'Promotion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1
  # DELETE /promotions/1.json
  def destroy
    @promotion = Promotion.find(params[:id])
    @promotion.destroy

    respond_to do |format|
      format.html { redirect_to promotions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlV1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "vendor/custom.modernizr" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
  <nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><a href="#">30 Day Promo! </a></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="center">
      <li class="divider"></li>
      <li> <%= link_to "New User", new_user_url%> </li>
      <li class="divider"></li>
      <li><%= link_to "New Promo", new_promotion_url%></li>
      <li class="divider"></li>
    </ul>
  </nav>

		<%= yield %>


</body>
</html>

app/views/promotions/_form.html.erb
<%= form_for(@promotion) do |f| %>
  <% if @promotion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promotion.errors.count, "error") %> prohibited this promotion from being saved:</h2>

      <ul>
      <% @promotion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %> (doesn't matter what this is)
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %> (use real email)
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :download_name %> (pick a name like flyer or brochure)
    <%= f.text_field :download_name %>
  </div>
  <div class="field">
    <%= f.label :download_link %> (use http://www.brighthope.org/downloads/misc_downloads/BH_BoardandKeyStaff.pdf)
    <%= f.text_field :download_link %>
  </div>
  <div class="field">
    <%= f.label :video_embed %> (use 21762736)
    <%= f.text_field :video_embed %>
  </div>
  <div class="field">
    <%= f.label :content %> (write whatever)
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :photo1 %> (use http://www.ruthlesslycreate.com/images/works/luckymonk/1.jpg)
    <%= f.text_field :photo1 %>
  </div>
  <div class="field">
    <%= f.label :photo2 %> (use http://www.ruthlesslycreate.com/images/works/luckymonk/2.jpg)
    <%= f.text_field :photo2 %>
  </div>
  <div class="field">
    <%= f.label :photo3 %> (use http://www.ruthlesslycreate.com/images/works/luckymonk/3.jpg)
    <%= f.text_field :photo3 %>
  </div>
  <div class="field">
    <%= f.label :photo4 %> (use http://www.ruthlesslycreate.com/images/works/luckymonk/4.jpg)
    <%= f.text_field :photo4 %>
  </div>
  <div class="field">
    <%= f.label :map_link %> (use http://goo.gl/maps/IhXGS)
    <%= f.text_area :map_link %>
  </div>
  <div class="field">
    <%= f.label :user_id %>
    <%= f.collection_select(:user_id, User.all, :id, :firstname) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promotions/edit.html.erb
<div class="row">
	<div class="large-9 columns">
		<h1>Editing promotion</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @promotion %> |
		<%= link_to 'Back', promotions_path %>
	</div>
</div>

app/views/promotions/index.html.erb
<h1>Listing promotions</h1>

<table>
  <tr>
    <th>Password</th>
    <th>Title</th>
    <th>Subtitle</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Download name</th>
    <th>Download link</th>
    <th>Video embed</th>
    <th>Content</th>
    <th>Photo1</th>
    <th>Photo2</th>
    <th>Photo3</th>
    <th>Photo4</th>
    <th>Map link</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @promotions.each do |promotion| %>
  <tr>
    <td><%= promotion.password %></td>
    <td><%= promotion.title %></td>
    <td><%= promotion.subtitle %></td>
    <td><%= promotion.phone %></td>
    <td><%= promotion.email %></td>
    <td><%= promotion.download_name %></td>
    <td><%= promotion.download_link %></td>
    <td><%= promotion.video_embed %></td>
    <td><%= promotion.content %></td>
    <td><%= promotion.photo1 %></td>
    <td><%= promotion.photo2 %></td>
    <td><%= promotion.photo3 %></td>
    <td><%= promotion.photo4 %></td>
    <td><%= promotion.map_link %></td>
    <td><%= promotion.user_id %></td>
    <td><%= link_to 'Show', promotion %></td>
    <td><%= link_to 'Edit', edit_promotion_path(promotion) %></td>
    <td><%= link_to 'Destroy', promotion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Promotion', new_promotion_path %>

app/views/promotions/new.html.erb
<div class="row">
	<div class="large-9 columns">
		<h1>New promotion</h1>

		<%= render 'form' %>

		<%= link_to 'Back', promotions_path %>
	</div>
</div>

app/views/promotions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="columns">
    <h1><%= @promotion.title %></h1>
    <h2><%= @promotion.subtitle %></h2>
  </div>
</div>

<div class="row">
  <div class="large-9 columns">

    <div class="flex-video widescreen vimeo">
      <iframe src="http://player.vimeo.com/video/<%= @promotion.video_embed %>?title=0&amp;byline=0&amp;portrait=0" width="400" height="225" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
    </div>

    <ul class="inline-list">
      <li><a><i class="icon-phone"></i> <%= @promotion.phone %></a></li>
      <li><a href="mailto:<%= @promotion.email %>"><i class="icon-envelope"></i> Send an Email</a></li>
      <li><a href="<%= @promotion.download_link %>"><i class="icon-download"></i> Download <%= @promotion.download_name %></a></li>
      <li><a href="<%= @promotion.map_link %>"><i class="icon-map-marker"></i> Map</a></li>
    </ul>


    <p>
      <%= @promotion.content %>
    </p>



    <ul class="clearing-thumbs" data-clearing>
      <li><a class="th" href="<%= @promotion.photo1 %>"><img src="<%= @promotion.photo1 %>"></a></li>
      <li><a class="th" href="<%= @promotion.photo2 %>"><img src="<%= @promotion.photo2 %>"></a></li>
      <li><a class="th" href="<%= @promotion.photo3 %>"><img src="<%= @promotion.photo3 %>"></a></li>
      <li><a class="th" href="<%= @promotion.photo4 %>"><img src="<%= @promotion.photo4 %>"></a></li>
    </ul>


    <ul class="inline-list">
      <li><a><i class="icon-phone"></i> <%= @promotion.phone %></a></li>
      <li><a href="mailto:<%= @promotion.email %>"><i class="icon-envelope"></i> Send an Email</a></li>
      <li><a href="<%= @promotion.download_link %>"><i class="icon-download"></i> Download <%= @promotion.download_name %></a></li>
      <li><a href="<%= @promotion.map_link %>"><i class="icon-map-marker"></i> Map</a></li>
    </ul>




  </div>
  <div class="large-3 columns">

    <p>
      <b>User:</b>
      <%= @promotion.user.firstname %>
    </p>

    <p>
      <b>Password:</b>
      <%= @promotion.password %>
    </p>

    <%= link_to 'Edit', edit_promotion_path(@promotion) %> |
    <%= link_to 'Back', promotions_path %>

  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.firstname %></td>
    <td><%= user.lastname %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="row">
  <div class="large-6 columns">
    <h1>New User</h1>

      <%= render 'form' %>

      <%= link_to 'Back', users_path %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @user.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @user.lastname %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>